# rpg_monster_rank_data.py
#
# === データ形式 ===
# Rank の値は2形式が混在:
#   - 文字列: 全カテゴリ共通のプロンプト（Common, Elite, Ancient, Mutated）
#   - dict:   カテゴリ別プロンプト（Boss, Legendary）
#       {
#           "default": "...",                   # 未定義カテゴリへのフォールバック
#           "by_category": {
#               "humanoid_small": "...",
#               "humanoid_large": "...",
#               ...
#           }
#       }
#
# === Rank プロンプトの方針 ===
# 種族 (:1.5) や属性 (:1.5) と互角に渡り合うため、Boss/Legendary の本質宣言を (:1.5)、
# 視覚フレーバーを (:1.4) で並走させる。
# サイズ語（colossal / massive / towering）は **large_creature 系カテゴリのみ** で使用し、
# small / amorphous / incorporeal 系では aura・close-up 構図・glowing eyes でサイズ非依存に威厳を出す。

MONSTER_RANK_DATA = {
    "Common": "simple and standard form, plain details, ordinary appearance",
    "Elite": "(elite battle-hardened veteran monster:1.4), (battle-worn scars and details on the body:1.3), imposing presence, {weathered iron|bronzed|scarred} accents on the form, signs of countless battles, alert combat-ready stance, slightly enlarged form",
    "Boss": {
        "default": "(epic boss monster, dramatic centerpiece of the image:1.5), (massive glowing energy aura surrounding the entire body:1.4), (intense glowing red eyes:1.4), debris and ember particles floating in mid-air around the form, dramatic backlighting, imposing menacing posture, dominant alpha predator presence, intense epic dramatic atmosphere",
        "by_category": {
            "humanoid_small": "(epic boss-tier small humanoid leader:1.5), (massive overwhelming dark aura around the small body:1.4), (intense glowing red eyes:1.4), debris and ember particles floating in mid-air, dramatic close-up framing filling the entire frame, intimidating menacing pose, ornate boss decoration on the body, ominous atmospheric haze",
            "humanoid_large": "(epic boss humanoid lord, dramatic centerpiece:1.5), (towering massive scale dwarfing surroundings:1.4), (intense glowing eyes:1.4), regal ornate armor and ceremonial weapons, debris and ember particles floating in mid-air, ground cracking under its weight, dramatic low-angle composition, imposing menacing posture, dominant alpha presence, intense epic dramatic atmosphere",
            "quadruped_small": "(epic boss-tier giant rodent alpha:1.5), (massive overwhelming dark aura around the body:1.4), (intense glowing red eyes, bared rodent teeth:1.4), snarling on four paws, debris and ember particles floating around, dramatic close-up framing, ornate scars and tribal marks on the fur",
            "quadruped_large": "(epic boss-tier alpha beast, dramatic centerpiece:1.5), (towering massive predator scale:1.4), (intense glowing eyes, bared fangs:1.4), dominant alpha posture on four legs, ground cracking, snarling, debris floating around the form, dramatic low-angle composition, intense epic atmosphere",
            "winged_mammal": "(epic boss bat creature, dramatic centerpiece:1.5), (massive impressive wingspan filling the frame:1.4), (intense glowing red eyes:1.4), aura of darkness around the body, debris and ember particles floating around the form, dramatic backlighting from below, ominous menacing presence",
            "winged_reptilian": "(epic boss-tier ancient dragon-kind, dramatic centerpiece:1.5), (colossal massive scaled beast filling the frame:1.4), (intense glowing eyes, breath of elemental energy:1.4), spreading wings dwarfing the surroundings, ground cracking under enormous weight, towering threatening presence, dramatic low-angle composition, ornate horns and crown of spikes",
            "serpentine": "(epic boss multi-headed serpent monster:1.5), (massive coiled serpentine body filling the frame:1.4), (all heads with intense glowing eyes:1.4), dripping venom from multiple fangs, intimidating spread of multiple heads, threatening titanic size, ornate scales pattern, dramatic composition",
            "arthropod": "(epic boss giant spider monster, dramatic centerpiece:1.5), (massive eight-legged arachnid:1.4), (all eight legs raised threateningly, glowing multiple eyes:1.4), webbing strands hanging around, dripping fangs, towering arachnid form, dramatic close-up framing, ominous atmosphere",
            "amphibian": "(epic boss bloated giant toad:1.5), (massive bloated amphibian body filling the frame:1.4), (inflated throat sac, glowing intense yellow eyes:1.4), sticky tongue ready to lash out, dominant predator presence on four legs, debris floating in murky water around, dramatic atmosphere",
            "amorphous": "(epic boss colossal amorphous slime monster:1.5), (massive towering pulsating mound:1.4), (pulsating glowing core inside the body, intense bright nucleus:1.4), debris and bones trapped inside the form, threatening swelling shape, ominous wobbling presence, dramatic close-up framing",
            "incorporeal": "(epic boss spectral being, dramatic centerpiece:1.5), (massive looming ethereal form filling the frame:1.4), (glowing piercing eyes from the void:1.4), swirling dark mist around, ghostly aura, no solid body but overwhelming oppressive presence, dramatic backlighting, ominous atmosphere",
            "construct_stone": "(epic boss massive stone gargoyle sentinel:1.5), (towering carved stone form:1.4), (glowing intense eyes carved into stone, ancient runes glowing:1.4), ancient sacred runes carved across the stone surface, imposing immortal statue presence, debris and dust floating around, dramatic low-angle composition",
            "construct_object": "(epic boss giant mimic monster, dramatic centerpiece:1.5), (massive transformed monstrous chest:1.4), (aggressive gaping maw with countless rows of teeth, glowing inner eyes:1.4), threatening enormous size, sticky tongue lashing out, ornate iron bands and gold trim on the chest, dramatic atmosphere",
            "tubular": "(epic boss colossal worm monster, dramatic centerpiece:1.5), (massive coiled tubular segmented body filling the frame:1.4), (enormous circular maw with rings of teeth, glowing inner depth:1.4), segmented pulsating body, threatening titanic size, slime dripping from the maw, dramatic close-up composition"
        }
    },
    "Legendary": {
        "default": "(legendary divine creature, mythical epic boss monster:1.5), (radiant golden divine aura emanating from the entire body:1.4), (swirling magical particles and motes of light surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the body|sacred celestial markings|cosmic constellation patterns}, {crown of light|halo of divine power|aura of stars}, masterwork ornate sacred decoration, supreme authority presence, transcendent divine majesty, mythical legendary epic atmosphere",
        "by_category": {
            "humanoid_small": "(legendary divine small humanoid, mythical epic monster:1.5), (radiant golden divine aura around the body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the skin|sacred celestial markings on the body|cosmic constellation patterns on the clothing}, {crown of light above the head|halo of divine power|aura of stars}, ornate sacred decoration, transcendent divine majesty",
            "humanoid_large": "(legendary divine humanoid lord, mythical epic monster:1.5), (radiant golden divine aura emanating from the towering body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the skin and ornate armor|sacred celestial markings on the armor|cosmic constellation patterns on cape}, {crown of light above the head|halo of divine power|aura of stars}, masterwork ornate sacred armor and weapons, transcendent divine majesty",
            "quadruped_small": "(legendary divine small beast, mythical epic creature:1.5), (radiant golden divine aura around the body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the fur|sacred celestial markings on the fur|cosmic constellation patterns on the body}, halo of divine light, ornate sacred decoration, transcendent divine majesty",
            "quadruped_large": "(legendary divine alpha beast, mythical epic creature:1.5), (radiant golden divine aura emanating from the massive body:1.4), (swirling magical particles surrounding the towering form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the fur|sacred celestial markings on the fur|cosmic constellation patterns covering the body}, {crown of light|halo of divine power|aura of stars}, masterwork ornate decoration, transcendent divine majesty",
            "winged_mammal": "(legendary divine bat creature, mythical sacred monster:1.5), (radiant golden divine aura around the body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the wing membranes|sacred celestial markings on the fur|cosmic constellation patterns on the wings}, halo of divine light, ornate sacred decoration on the body, mythical legendary atmosphere",
            "winged_reptilian": "(legendary divine ancient dragon-kind, mythical epic monster:1.5), (radiant golden divine aura emanating from the colossal body:1.4), (swirling magical particles surrounding the towering form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the scales|sacred celestial markings on the wings|cosmic constellation patterns on the body}, {crown of light above the head|halo of divine power|aura of stars}, masterwork ornate horns and decoration, transcendent divine majesty",
            "serpentine": "(legendary divine multi-headed serpent, mythical sacred monster:1.5), (radiant golden divine aura emanating from the coiled body:1.4), (swirling magical particles surrounding the form:1.4), (all heads with intense glowing eyes of otherworldly power:1.4), {glowing golden runes etched into the scales|sacred celestial markings on the body|cosmic constellation patterns}, halos of divine power around each head, transcendent divine majesty",
            "arthropod": "(legendary divine arachnid, mythical sacred monster:1.5), (radiant golden divine aura around the body:1.4), (swirling magical particles surrounding the form:1.4), (multiple intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the chitin|sacred celestial markings on the carapace|cosmic constellation patterns on the legs}, halo of divine light, ornate sacred decoration, mythical legendary atmosphere",
            "amphibian": "(legendary divine amphibian, mythical sacred monster:1.5), (radiant golden divine aura around the bloated body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes etched into the warty skin|sacred celestial markings on the body|cosmic constellation patterns}, halo of divine light, ornate sacred decoration, mythical atmosphere",
            "amorphous": "(legendary divine amorphous spirit, mythical sacred monster:1.5), (radiant golden divine aura emanating from the entire form:1.4), (swirling magical particles inside and around the body:1.4), (intense glowing core with otherworldly power:1.4), {glowing golden runes floating within the form|sacred celestial markings|cosmic constellation patterns visible inside}, halo of divine light, transcendent ethereal majesty",
            "incorporeal": "(legendary divine spectral being, mythical sacred monster:1.5), (radiant golden divine aura emanating from the ethereal form:1.4), (swirling magical particles surrounding the wispy form:1.4), (intense glowing eyes with otherworldly power:1.4), {glowing golden runes floating around the form|sacred celestial markings|cosmic constellation patterns of light}, {crown of light|halo of divine power|aura of stars}, transcendent divine majesty",
            "construct_stone": "(legendary divine stone sentinel, mythical sacred construct:1.5), (radiant golden divine aura emanating from the carved stone body:1.4), (swirling magical particles surrounding the form:1.4), (intense glowing eyes carved into stone with otherworldly power:1.4), {glowing golden sacred runes carved into the stone|celestial markings on the surface|cosmic constellation patterns}, halo of divine power, masterwork ornate carved decoration, transcendent divine majesty",
            "construct_object": "(legendary divine mimic, mythical sacred treasure monster:1.5), (radiant golden divine aura around the chest body:1.4), (swirling magical particles surrounding the form:1.4), (glowing inner eyes with otherworldly power:1.4), {glowing golden runes etched into the wooden surface|sacred celestial markings|cosmic constellation patterns}, ornate sacred gold and gem decoration, transcendent divine majesty",
            "tubular": "(legendary divine colossal worm, mythical sacred monster:1.5), (radiant golden divine aura emanating from the segmented body:1.4), (swirling magical particles surrounding the towering form:1.4), (glowing inner depth of the maw with otherworldly power:1.4), {glowing golden runes etched into the segmented skin|sacred celestial markings|cosmic constellation patterns}, halo of divine light, transcendent divine majesty"
        }
    },
    "Ancient": "(ancient primordial creature of forgotten eras:1.4), (covered in dust, age-old moss, and weathered patina:1.3), weathered ancient surface with deep cracks, {worn battle scars|cracked overgrown form|patina of millennia}, wise primordial presence, imposing aged form, traces of lost civilizations on the body",
    "Mutated": "(mutated aberrant abomination:1.4), (unnatural growths and protrusions covering the body:1.3), {crystalline|jagged|fleshy} growths protruding from the body, asymmetric thorns and tumorous protrusions, pulsating mutated aura, {bulging veins|fused extra limbs|grotesque overgrowth}, aberrant deformed anatomy, unsettling wrong presence",
}
